export const loginConst =  {
  ACTION_CHANGE_EMAIL: 'ACTION_CHANGE_EMAIL',
  ACTION_CHANGE_PASSWORD: 'ACTION_CHANGE_PASSWORD',
};

export const signUpConst =  {
  ACTION_CHANGE_FIRST_NAME: 'ACTION_CHANGE_FIRST_NAME',
  ACTION_CHANGE_LAST_NAME: 'ACTION_CHANGE_LAST_NAME',
  ACTION_CHANGE_EMAIL: 'ACTION_CHANGE_EMAIL',
  ACTION_CHANGE_PASSWORD: 'ACTION_CHANGE_PASSWORD',
  ACTION_CHANGE_PASSWORD_CONFIRM: 'ACTION_CHANGE_PASSWORD_CONFIRM'
};


